#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

# Free up disk space on GitHub Actions runners

if [[ -z "${GITHUB_ACTIONS:-}" ]]; then
  echo "Not running on GitHub Actions; skipping disk space cleanup (for safety)"
  exit 0
fi

echo "Before cleanup:"
df -h /

sudo rm -rf /opt/hostedtoolcache/*  # remove pre-installed tool versions
sudo rm -rf /usr/share/dotnet
sudo docker system prune -af || true

echo "After cleanup:"
df -h /